# Site Configs

# url: http://blog.geuer-pollmann.de/
url: ""


name: Tintenfleck
author: Tintenfleck
sitetitle: Tintenfleck Blog
description: Tintenfleck Blog

# 
# Themes from http://bootswatch.com/
# amelia, cerulean, cosmo, cyborg, flatly, journal, readable, simplex, slate, spacelab, united, yeti
#
# bootswatchtheme: "amelia"
bootswatchtheme: "journal"

safe: true
lsi: false
encoding: UTF-8
markdown: redcarpet
markdown_ext:  md,markdown
pygments: true
set :markdown, fenced_code_blocks: true
